-- Recently viewed restaurants per user (ordered int array, newest first)
alter table public.profiles
  add column if not exists recently_viewed_restaurants integer[] not null default '{}';

comment on column public.profiles.recently_viewed_restaurants is
  'Ordered list of recently viewed restaurant IDs (newest first), max enforced by app';

-- Carousel/hero media slides per restaurant
create table if not exists public.restaurant_media_slides (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  position integer not null default 0,
  image_url text,
  menu_item_id bigint references public.menu_items(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint restaurant_media_slides_has_media check (coalesce(nullif(trim(image_url), ''), '') <> '' or menu_item_id is not null)
);

create index if not exists restaurant_media_slides_restaurant_position_idx
  on public.restaurant_media_slides (restaurant_id, position);

create or replace function public.set_restaurant_media_slides_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_restaurant_media_slides_updated_at on public.restaurant_media_slides;
create trigger trg_restaurant_media_slides_updated_at
before update on public.restaurant_media_slides
for each row
execute function public.set_restaurant_media_slides_updated_at();

alter table public.restaurant_media_slides enable row level security;

drop policy if exists "restaurant_media_slides public read" on public.restaurant_media_slides;
create policy "restaurant_media_slides public read"
on public.restaurant_media_slides
for select
using (true);

drop policy if exists "restaurant_media_slides owner manage" on public.restaurant_media_slides;
create policy "restaurant_media_slides owner manage"
on public.restaurant_media_slides
for all
using (
  exists (
    select 1
    from public.restaurant_staff rs
    where rs.restaurant_id = restaurant_media_slides.restaurant_id
      and rs.user_id = auth.uid()
      and lower(trim(rs.role)) in ('owner', 'admin')
  )
  or exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(trim(coalesce(p.role, ''))) = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.restaurant_staff rs
    where rs.restaurant_id = restaurant_media_slides.restaurant_id
      and rs.user_id = auth.uid()
      and lower(trim(rs.role)) in ('owner', 'admin')
  )
  or exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(trim(coalesce(p.role, ''))) = 'admin'
  )
);
