begin;

create table if not exists public.restaurant_menu_tags (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  key text not null,
  label text not null,
  color text not null,
  bg text not null,
  border text not null,
  enabled boolean not null default true,
  position integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (restaurant_id, key)
);

create index if not exists idx_restaurant_menu_tags_restaurant_position
  on public.restaurant_menu_tags (restaurant_id, position);

create or replace function public.set_restaurant_menu_tags_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_restaurant_menu_tags_updated_at on public.restaurant_menu_tags;
create trigger trg_restaurant_menu_tags_updated_at
before update on public.restaurant_menu_tags
for each row
execute function public.set_restaurant_menu_tags_updated_at();

alter table public.restaurant_menu_tags enable row level security;

drop policy if exists "Public can read restaurant menu tags" on public.restaurant_menu_tags;
create policy "Public can read restaurant menu tags"
  on public.restaurant_menu_tags
  for select
  to anon, authenticated
  using (true);

create or replace function public.set_restaurant_menu_tags(
  p_restaurant_id bigint,
  p_tags jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  inserted_count integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if not (
    public.is_platform_admin()
    or p_restaurant_id = public.get_my_restaurant_id()
    or exists (
      select 1
      from public.restaurants r
      where r.id = p_restaurant_id
        and r.owner_id = auth.uid()
    )
  ) then
    raise exception 'Not allowed to edit menu tags for this restaurant';
  end if;

  if p_tags is null or jsonb_typeof(p_tags) <> 'array' then
    raise exception 'p_tags must be a JSON array';
  end if;

  delete from public.restaurant_menu_tags where restaurant_id = p_restaurant_id;

  insert into public.restaurant_menu_tags (
    restaurant_id,
    key,
    label,
    color,
    bg,
    border,
    enabled,
    position
  )
  select
    p_restaurant_id,
    coalesce(
      nullif(regexp_replace(lower(trim(coalesce(item->>'key', item->>'label', ''))), '[^a-z0-9]+', '_', 'g'), ''),
      'main_course'
    ) as key,
    coalesce(nullif(trim(item->>'label'), ''), 'Main Course') as label,
    coalesce(nullif(item->>'color', ''), '#F97316') as color,
    coalesce(nullif(item->>'bg', ''), 'bg-orange-500/10') as bg,
    coalesce(nullif(item->>'border', ''), 'border-orange-500/30') as border,
    case
      when lower(coalesce(item->>'enabled', 'true')) in ('false', '0', 'no') then false
      else true
    end as enabled,
    coalesce(nullif(item->>'position', '')::integer, ordinality - 1) as position
  from jsonb_array_elements(p_tags) with ordinality as elems(item, ordinality)
  where jsonb_typeof(item) = 'object'
  on conflict (restaurant_id, key)
  do update set
    label = excluded.label,
    color = excluded.color,
    bg = excluded.bg,
    border = excluded.border,
    enabled = excluded.enabled,
    position = excluded.position,
    updated_at = timezone('utc', now());

  get diagnostics inserted_count = row_count;

  if not exists (
    select 1 from public.restaurant_menu_tags where restaurant_id = p_restaurant_id
  ) then
    insert into public.restaurant_menu_tags (
      restaurant_id, key, label, color, bg, border, enabled, position
    ) values (
      p_restaurant_id,
      'main_course',
      'Main Course',
      '#818CF8',
      'bg-indigo-500/10',
      'border-indigo-500/30',
      true,
      0
    );
    inserted_count := inserted_count + 1;
  end if;

  return inserted_count;
end;
$$;

comment on function public.set_restaurant_menu_tags(bigint, jsonb)
  is 'Replaces all menu tags for a restaurant. Uses SECURITY DEFINER + helper checks to avoid RLS recursion/write failures.';

revoke all on function public.set_restaurant_menu_tags(bigint, jsonb) from public;
grant execute on function public.set_restaurant_menu_tags(bigint, jsonb) to authenticated;
grant execute on function public.set_restaurant_menu_tags(bigint, jsonb) to service_role;

do $$
declare
  has_menu_tag_config boolean;
begin
  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'restaurants'
      and column_name = 'menu_tag_config'
  ) into has_menu_tag_config;

  if has_menu_tag_config then
    insert into public.restaurant_menu_tags (
      restaurant_id,
      key,
      label,
      color,
      bg,
      border,
      enabled,
      position
    )
    select
      r.id,
      coalesce(
        nullif(regexp_replace(lower(trim(coalesce(tag->>'key', tag->>'label', ''))), '[^a-z0-9]+', '_', 'g'), ''),
        'main_course'
      ) as key,
      coalesce(nullif(trim(tag->>'label'), ''), 'Main Course') as label,
      coalesce(nullif(tag->>'color', ''), '#F97316') as color,
      coalesce(nullif(tag->>'bg', ''), 'bg-orange-500/10') as bg,
      coalesce(nullif(tag->>'border', ''), 'border-orange-500/30') as border,
      case
        when lower(coalesce(tag->>'enabled', 'true')) in ('false', '0', 'no') then false
        else true
      end as enabled,
      coalesce(nullif(tag->>'position', '')::integer, ordinality - 1) as position
    from public.restaurants r
    cross join lateral jsonb_array_elements(coalesce(r.menu_tag_config, '[]'::jsonb)) with ordinality as elems(tag, ordinality)
    where jsonb_typeof(tag) = 'object'
    on conflict (restaurant_id, key)
    do update set
      label = excluded.label,
      color = excluded.color,
      bg = excluded.bg,
      border = excluded.border,
      enabled = excluded.enabled,
      position = excluded.position,
      updated_at = timezone('utc', now());
  end if;

  insert into public.restaurant_menu_tags (
    restaurant_id, key, label, color, bg, border, enabled, position
  )
  select
    r.id,
    'main_course',
    'Main Course',
    '#818CF8',
    'bg-indigo-500/10',
    'border-indigo-500/30',
    true,
    0
  from public.restaurants r
  where not exists (
    select 1
    from public.restaurant_menu_tags t
    where t.restaurant_id = r.id
  );
end $$;

commit;
