begin;

create table if not exists public.user_cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, restaurant_id, menu_item_id)
);

create index if not exists idx_user_cart_items_user on public.user_cart_items(user_id);
create index if not exists idx_user_cart_items_restaurant on public.user_cart_items(restaurant_id);
create index if not exists idx_user_cart_items_menu_item on public.user_cart_items(menu_item_id);

create or replace function public.set_user_cart_items_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_user_cart_items_updated_at on public.user_cart_items;
create trigger trg_user_cart_items_updated_at
before update on public.user_cart_items
for each row
execute function public.set_user_cart_items_updated_at();

alter table public.user_cart_items enable row level security;

drop policy if exists "Users read own cart items" on public.user_cart_items;
create policy "Users read own cart items"
  on public.user_cart_items
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users insert own cart items" on public.user_cart_items;
create policy "Users insert own cart items"
  on public.user_cart_items
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users update own cart items" on public.user_cart_items;
create policy "Users update own cart items"
  on public.user_cart_items
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users delete own cart items" on public.user_cart_items;
create policy "Users delete own cart items"
  on public.user_cart_items
  for delete
  to authenticated
  using (auth.uid() = user_id);

commit;

